[wordpress]
vm1 ansible_host=192.168.56.10 ansible_user=vagrant ansible_port=22 ansible_private_key_file=/mnt/c/Users/DELL/OneDrive/Documents/Projet-TF/TP-Terraform/tp-virtualbox/vagrant/.vagrant/machines/vm1/virtualbox/private_key ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
